owner: BasiraLimted # Our GitHub organization where this repository lives
repo: basirastate # The name of this repository

assignees: # Users to assign downtime issues (optional)
  - rufilboy

sites:
  - name: Basira App
    url: https://www.basira.app
  - name: Basira Stage App
    url: https://stage.market.basira.app
  - name: Market Basira
    url: https://market.basira.app
  - name: Live API
    url: https://api.basira.app
  - name: Stage API
    url: https://stage.api.basira.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: monitor.basira.app
  baseUrl: /basirastate
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Basira Upptime
  introTitle: Monitoring of **Basira App** using upptime
  introMessage: This is a status page for Basira App which uses **real-time** data from our [GitHub repository](https://github.com/BasiraLimted/basirastate).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
